platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # Firebase dependencies
  pod 'FirebaseCore', '12.15.0'
  pod 'FirebaseAuth', '12.15.0'
  pod 'FirebaseFirestoreInternal', '12.15.0'
  pod 'FirebaseStorage', '12.15.0'
  pod 'FirebaseMessaging', '12.15.0'
  pod 'FirebaseAnalytics', '12.15.0'
  pod 'FirebaseRemoteConfig', '12.15.0'
  pod 'FirebaseCrashlytics', '12.15.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
